Opetushallitus/omatsivut

src/main/resources/translations/fi.json
=> Tekstimuutos infoNotification

src/main/resources/translations/en.json
=> infoNotification tekstimuutos

pom.xml
It reads the single study place enforcement from Tarjonta.
See 
* https://github.com/Opetushallitus/hakemuseditori/pull/2
* https://github.com/Opetushallitus/tarjonta/pull/5
=> Use new hakemuseditori version

src/main/less/preview.less, src/main/scala/fi/vm/sade/omatsivut/hakemuspreview/HakemusPreviewGenerator.scala
Hakukohderyhmäkohtaiset Richtextit dekoodattuna takaisin html:ksi.
=> BUG-1335 html dekoodaus richtextiin

hakemuseditori/src/main/js/directives/valintatulos.js, hakemuseditori/src/main/js/hakemus.js, hakemuseditori/src/main/templates/kela.html, pom.xml, src/main/webapp/test/page/applicationListPage.js, src/main/webapp/test/page/hakutoiveidenMuokkausPage.js, src/main/webapp/test/runner.html, src/main/webapp/test/spec/applicationListSpec.js
=> Valintarekisteri psql test data

src/main/js/directives/applicationList.js, src/main/js/restResources.js, src/main/less/main.less, src/main/resources/translations/en.json, src/main/resources/translations/fi.json, src/main/resources/translations/sv.json, src/main/scala/fi/vm/sade/ataru/AtaruServiceComponent.scala, src/main/scala/fi/vm/sade/hakemuseditori/hakemus/HakemusInfo.scala, src/main/scala/fi/vm/sade/omatsivut/servlet/ApplicationsServlet.scala, src/main/templates/applicationList.html, src/main/webapp/test/spec/applicationListSpec.js, src/main/webapp/test/util/testHelpers.js, src/test/scala/fi/vm/sade/omatsivut/hakemus/GetApplicationsSpec.scala, src/test/scala/fi/vm/sade/omatsivut/hakemus/HakemusApiSpecification.scala
Don't return 500 when ataru is down. Instead return hakuapp applications.
=> Handle ataru not online

pom.xml, src/main/scala/fi/vm/sade/hakemuseditori/HakemusEditori.scala, src/main/scala/fi/vm/sade/hakemuseditori/auditlog/AuditEvent.scala, src/main/scala/fi/vm/sade/hakemuseditori/auditlog/AuditLogUtils.scala, src/main/scala/fi/vm/sade/hakemuseditori/auditlog/AuditLogger.scala, src/main/scala/fi/vm/sade/hakemuseditori/auditlog/FetchTuloskirje.scala, src/main/scala/fi/vm/sade/hakemuseditori/auditlog/OmatSivutOperation.scala, src/main/scala/fi/vm/sade/hakemuseditori/auditlog/Operation.scala, src/main/scala/fi/vm/sade/hakemuseditori/auditlog/SaveVastaanotto.scala, src/main/scala/fi/vm/sade/hakemuseditori/auditlog/ShowHakemus.scala, src/main/scala/fi/vm/sade/hakemuseditori/auditlog/UpdateHakemus.scala, src/main/scala/fi/vm/sade/hakemuseditori/hakemus/HakemusRepositoryComponent.scala, src/main/scala/fi/vm/sade/hakemuseditori/viestintapalvelu/TuloskirjeComponent.scala, src/main/scala/fi/vm/sade/omatsivut/auditlog/Login.scala, src/main/scala/fi/vm/sade/omatsivut/auditlog/Logout.scala, src/main/scala/fi/vm/sade/omatsivut/config/ComponentRegistry.scala, src/main/scala/fi/vm/sade/omatsivut/hakemuspreview/HakemusPreviewGenerator.scala, src/main/scala/fi/vm/sade/omatsivut/servlet/ApplicationsServlet.scala, src/main/scala/fi/vm/sade/omatsivut/servlet/AuditLoginFilter.scala, src/main/scala/fi/vm/sade/omatsivut/servlet/FixtureServlet.scala, src/main/scala/fi/vm/sade/omatsivut/servlet/NonSensitiveApplicationServlet.scala, src/main/scala/fi/vm/sade/omatsivut/servlet/session/LogoutServlet.scala, src/main/scala/fi/vm/sade/omatsivut/servlet/session/SecuredSessionServlet.scala
Login ja Logout on ainoat, missä lokitetaan täydet tiedot käyttäjästä (oid, inetaddress, session, user-agent).
Muissa pelkästään oidi: new User(getOid(userOid).orNull, null, null, null).
=> Upgrade auditlogger to 8.0.0-SNAPSHOT

src/main/resources/oph-configuration/log4j.properties.template.aws
Update new package and class names to log4j.properties.
=> BUG-1701 : Fix audit log config

src/main/scala/fi/vm/sade/omatsivut/servlet/LanguageFilter.scala
requestUrlissa on AWS:n myötä aina alb.testiopintopolku.fi, joten oikea url täytyy tarkistaa headeristä X-Forwarded-Host.
=> BUG-1788  kieli aina suomi

LICENSE.txt, pom.xml, src/main/js/directives/ilmoittautuminen.html, src/main/js/directives/ilmoittautuminen.js, src/main/js/directives/kela.html, src/main/js/models/hakemus.js, src/main/less/hakemuseditori/templates/ilmoittautuminen.less, src/main/resources/hakemuseditorimockdata/applications-ataru.json, src/main/resources/hakemuseditorimockdata/hakukohteet.json, src/main/resources/translations/en.json, src/main/resources/translations/fi.json, src/main/resources/translations/sv.json, src/main/scala/fi/vm/sade/ataru/AtaruServiceComponent.scala, src/main/scala/fi/vm/sade/hakemuseditori/hakemus/HakemusConverter.scala, src/main/scala/fi/vm/sade/hakemuseditori/hakemus/domain/package.scala, src/main/scala/fi/vm/sade/hakemuseditori/oppijanumerorekisteri/oppijanumerorekisteri.scala, src/main/scala/fi/vm/sade/hakemuseditori/tarjonta/TarjontaComponent.scala, src/main/scala/fi/vm/sade/hakemuseditori/tarjonta/TarjontaParser.scala, src/main/scala/fi/vm/sade/hakemuseditori/tarjonta/domain/package.scala, src/main/webapp/test/page/applicationListPage.js, src/main/webapp/test/spec/applicationListSpec.js, src/test/scala/fi/vm/sade/omatsivut/hakemus/GetApplicationsSpec.scala, src/test/scala/fi/vm/sade/omatsivut/hakemus/NonSensitiveApplicationSpec.scala
Katsotaan, jos saadaan parempi diffi kuin https://github.com/Opetushallitus/omatsivut/pull/98/files :ssa.
=> OK-197 :  take two

pom.xml, src/main/js/app.js, src/main/scala/ScalatraBootstrap.scala, src/main/scala/fi/vm/sade/ataru/AtaruServiceComponent.scala, src/main/scala/fi/vm/sade/hakemuseditori/oppijanumerorekisteri/oppijanumerorekisteri.scala, src/main/scala/fi/vm/sade/omatsivut/config/ComponentRegistry.scala, src/main/scala/fi/vm/sade/omatsivut/oppijantunnistus/OppijanTunnistus.scala, src/main/scala/fi/vm/sade/omatsivut/security/AuthenticationInfoService.scala, src/main/scala/fi/vm/sade/omatsivut/servlet/ApplicationsServlet.scala, src/main/scala/fi/vm/sade/omatsivut/servlet/LanguageFilter.scala, src/main/scala/fi/vm/sade/omatsivut/servlet/ScalatraFilterWithWhitelist.scala
...for example, if CAS just rebooted.
See also: https://github.com/Opetushallitus/scala-utils/pull/15, https://github.com/Opetushallitus/scala-utils/pull/16
Also whitelisted HealthServlet in LanguageFilter to stop health checks from spamming WARN level logs
=> BUG-1987 update scala-cas: retry TGT/ST once if fails

package.json, src/main/js/directives/application.html, src/main/js/directives/applicationPeriods.html, src/main/js/directives/formattedTime.js, src/main/js/directives/hakutoiveenVastaanotto.js, src/main/js/directives/hakutoiveet.html, src/main/js/moment.js, src/main/webapp/test/spec/applicationListSpec.js
Formaatti:
LLL Z = `1. joulukuuta 2100 klo 07.00 +02:00`
korvataan +02:00 -> (EET), +03:00 -> (EEST), esim:
`1. joulukuuta 2100 klo 07.00 (EET)`
ks. myös https://momentjs.com/timezone/
=> OK-217  show timezones

src/main/components/lasnaoloilmoittautuminen/lasnaoloilmoittautuminen.html, src/main/components/lasnaoloilmoittautuminen/lasnaoloilmoittautuminen.less
Läsnäoloilmoittautumisnappulaa voi painaa vastaa tehtyään jonkin läsnäolokausivalinnan.
=> Ok 237 disable

pom.xml
Update java-http, scala-cas, scala-group-emailer
=> OK-241  caller-id

src/main/scala/fi/vm/sade/omatsivut/vastaanotto/VastaanottoService.scala
Tallennetaan vastaanotto aina hakemukselta löytyvälle henkiloOidille. Logitetaan tilanteessa, jossa ennen oltaisiin tallennettu jollekin muulle oidille kuin hakemukselta löytyvälle.
=> Bug 2183 vastaanotto hakemuksen oidille

pom.xml
Mongodriverin ja hakemus-apin päivitys hakulomakemongon DocumentDB-siirtoa varten.
=> Päivitä riippuvuudet documentdb-mongoa varten

src/main/js/directives/valintatulos.html
Valinta-tulos-service has been modified to only show relevant pistees
=> OY-3087 Show also negative pistees if available

README.md, pom.xml, src/main/js/directives/valintatulos.html, src/main/less/hakemuseditori/templates/valintatulos.less, src/main/scala/fi/vm/sade/omatsivut/config/AppConfig.scala, src/test/scala/fi/vm/sade/omatsivut/mocha/OmatSivutMochaTest.scala
Yritän vielä ratkaista tuota testien ajoon ci:llä liittyvää ongelmaa.
=> OY-4335  valintatapajonojen pisteiden tekstit

.gitignore, package-lock.json, src/main/js/controllers/hakutoiveidenMuokkaus.js, src/main/js/interceptors/nonSensitiveHakemus.js, src/main/js/util.js
Vaihdetaan bearer tokenin säilytys session storagesta cookieen.
=> Oy 4348 securelink selain korjaus

.github/workflows/build.yml
=> update build file 3rd party action versions and add new deploy command
